import os
from dotenv import load_dotenv

load_dotenv()

SOCIAL_NETWORK_LOGIN = os.getenv("SOCIAL_NETWORK_LOGIN")
SOCIAL_NETWORK_EMAIL = os.getenv("SOCIAL_NETWORK_EMAIL")
SOCIAL_NETWORK_PASSWORD = os.getenv("SOCIAL_NETWORK_PASSWORD")

SOCIAL_NETWORK_FIRST_NAME = os.getenv("SOCIAL_NETWORK_FIRST_NAME")
SOCIAL_NETWORK_LAST_NAME = os.getenv("SOCIAL_NETWORK_LAST_NAME")
SOCIAL_NETWORK_LINKEDIN = os.getenv("SOCIAL_NETWORK_LINKEDIN")
SOCIAL_NETWORK_FACEBOOK = os.getenv("SOCIAL_NETWORK_FACEBOOK")

CHROME_DRIVER_PATH = os.getenv("CHROME_DRIVER_PATH")

SOCIAL_NETWORK_PORT = os.getenv("SOCIAL_NETWORK_PORT")
SOCIAL_NETWORK_HOST = os.getenv("SOCIAL_NETWORK_HOST")
